controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\RegistrationController::register

program:
    path: /program
    controller: App\Controller\ProgramController::index